version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: mozzarella_prod_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mozzarella
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mozzarella"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - ./backend/.env.prod
    ports:
      - "3000:3000"
    depends_on: 
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8080:80" # Nginx en el contenedor expone el puerto 80
    depends_on:
      - backend

volumes:
  postgres_data: