version: '3.8'

services:
  postgres-db:
    image: postgis/postgis:15-3.3
    container_name: mozzarella_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: America/Merida
      POSTGRES_DB: mozzarella_cloud_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: