services:
  db:
    image: postgis/postgis:13-3.1
    container_name: mozzarella_cloud_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pG_sTr0nPa55w0rd_f0r_M0zz4r3ll4!
      POSTGRES_DB: mozzarella_new
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: