services:
  db:
    image: postgis/postgis:13-3.1
    container_name: mozzarella_cloud_db
    restart: always
    environment:
      POSTGRES_USER: codespace
      POSTGRES_DB: mozzarella_new
      POSTGRES_HOST_AUTH_METHOD: trust # Allow password-less connections for local development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codespace -d mozzarella_new"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: